// react/src/App.tsx
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { fontPairings } from '$lib/fonts';
import { usePreferences } from './hooks/usePreferences';
import { WeatherProvider } from './hooks/useWeather';
import WeatherScreen from './components/WeatherScreen';
import './App.css';
import './components/components.css';

function AppInner() {
	const { i18n } = useTranslation();
	const { fontIndex } = usePreferences();
	const [fontUrl, setFontUrl] = useState('');
	const [displayFamily, setDisplayFamily] = useState('system-ui, sans-serif');
	const [bodyFamily, setBodyFamily] = useState('system-ui, sans-serif');
	const [fontFeatures, setFontFeatures] = useState('normal');

	useEffect(() => {
		const pairing = fontPairings[fontIndex];
		if (pairing) {
			setFontUrl(pairing.googleFontsUrl ?? '');
			setDisplayFamily(pairing.displayFamily);
			setBodyFamily(pairing.bodyFamily);
			setFontFeatures(pairing.bodyFontFeatures ?? 'normal');
		}
	}, [fontIndex]);

	const isReady = i18n.isInitialized;

	if (!isReady) {
		return (
			<div className="loading-shell">
				<div className="spinner" />
			</div>
		);
	}

	return (
		<>
			{fontUrl && <link href={fontUrl} rel="stylesheet" />}
			<div
				className="app-shell"
				style={{
					'--font-display': displayFamily,
					'--font-body': bodyFamily,
					'--font-features': fontFeatures,
				} as React.CSSProperties}
			>
				<WeatherProvider>
					<WeatherScreen />
				</WeatherProvider>
			</div>
		</>
	);
}

export default AppInner;

// angular/src/app/app.component.ts
import { Component, inject, computed, effect } from '@angular/core';
import { fontPairings } from '$lib/fonts';
import { PreferencesService } from './services/preferences.service';
import { WeatherScreenComponent } from './components/weather-screen.component';

@Component({
	selector: 'app-root',
	standalone: true,
	imports: [WeatherScreenComponent],
	template: `
		@if (fontUrl()) {
			<link [href]="fontUrl()" rel="stylesheet" />
		}
		<div class="app-shell"
			[style.--font-display]="displayFamily()"
			[style.--font-body]="bodyFamily()"
			[style.--font-features]="fontFeatures()">
			<app-weather-screen />
		</div>
	`,
	styles: `
		.app-shell {
			width: 100%;
			height: 100dvh;
			background: linear-gradient(to bottom, #0E0B3D, #1A1565);
			position: relative;
			overflow: hidden;
			font-family: var(--font-body);
		}
	`,
})
export class AppComponent {
	private prefs = inject(PreferencesService);

	fontUrl = computed(() => fontPairings[this.prefs.fontIndex()].googleFontsUrl ?? '');
	displayFamily = computed(() => fontPairings[this.prefs.fontIndex()].displayFamily);
	bodyFamily = computed(() => fontPairings[this.prefs.fontIndex()].bodyFamily);
	fontFeatures = computed(() => fontPairings[this.prefs.fontIndex()].bodyFontFeatures ?? 'normal');
}
